// See LICENSE file for copyright and license details
//
// Oracle-vector testbench for the postencoder.
//
// Checks the postencoder against an INDEPENDENT golden reference generated by
// tools/takum_oracle.py.  The vector file holds, in order:
//   * every (sign, characteristic, mantissa) tuple obtained by decoding each
//     representable takum -> the encoder must reproduce that takum, and
//   * explicit boundary tuples (characteristic = -255 and +254 with
//     rounding-forcing mantissas) that exercise the underflow/overflow
//     saturation path the roundtrip vectors never reach.  This is the path
//     where the historical sign-of-underflow bug lived, so it is checked
//     directly here rather than implicitly.
//
// Each vector line is:  sign  characteristic  mantissa  is_zero  is_nar  expected_takum
// (mantissa and expected_takum in binary, characteristic signed decimal).
//
// Compile per width with  iverilog -g2012 -P postencoder_tb.N=8 ...
// and pass the vector file with  +VEC=<path>.

`timescale 1ns / 1ps

module postencoder_tb #(
    parameter int N = 16
);

    logic              sign_bit;
    logic signed [8:0] characteristic;
    logic [N-6:0]      mantissa_bits;
    logic              is_zero;
    logic              is_nar;
    logic [N-1:0]      takum;

    postencoder #(
        .N(N)
    ) dut (
        .sign_bit       (sign_bit),
        .characteristic (characteristic),
        .mantissa_bits  (mantissa_bits),
        .is_zero        (is_zero),
        .is_nar         (is_nar),
        .takum          (takum)
    );

    integer fd, code, errors, count;
    string  vecfile;

    integer       s_ref, c_ref, iz_ref, inar_ref;
    logic [N-6:0] mant_ref;
    logic [N-1:0] takum_ref;

    initial begin
        errors = 0;
        count  = 0;
        if (!$value$plusargs("VEC=%s", vecfile)) begin
            $display("FATAL: no +VEC=<file> given");
            $fatal;
        end
        fd = $fopen(vecfile, "r");
        if (fd == 0) begin
            $display("FATAL: cannot open %s", vecfile);
            $fatal;
        end

        while (!$feof(fd)) begin
            code = $fscanf(fd, "%d %d %b %d %d %b\n",
                           s_ref, c_ref, mant_ref, iz_ref, inar_ref, takum_ref);
            if (code != 6) continue;

            sign_bit       = s_ref[0];
            characteristic = c_ref;            // signed assignment, fits 9-bit range
            mantissa_bits  = mant_ref;
            is_zero        = iz_ref[0];
            is_nar         = inar_ref[0];
            #1;
            count = count + 1;

            if (takum !== takum_ref) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("MISMATCH s=%0d c=%0d mant=%b rtl=%b ref=%b",
                             s_ref, c_ref, mant_ref, takum, takum_ref);
            end
        end
        $fclose(fd);

        if (errors == 0)
            $display("PASS: postencoder N=%0d, %0d vectors, 0 mismatches.", N, count);
        else
            $display("FAIL: postencoder N=%0d, %0d vectors, %0d mismatches.", N, count, errors);
    end

endmodule
