// See LICENSE file for copyright and license details
//
// Oracle-vector testbench for the predecoder.
//
// Unlike a self-referential rtl-vs-behave comparison (which can share a
// conversion error in both models and pass falsely), this testbench checks the
// synthesizable predecoder against an INDEPENDENT golden reference generated by
// tools/takum_oracle.py straight from the takum algebraic specification.
//
// Each vector line is:  takum  sign  characteristic  mantissa  precision  is_zero  is_nar
// (takum and mantissa in binary, characteristic signed decimal).
//
// Compile per width with e.g.  iverilog -g2012 -P predecoder_tb.N=8 ...
// and pass the vector file with  +VEC=<path>.  OUTPUT_EXPONENT is fixed to 0
// (logarithmic / characteristic), matching the generated vectors.

`timescale 1ns / 1ps

module predecoder_tb #(
    parameter int N = 16
);

    logic [N-1:0]           takum;
    logic                   sign_bit;
    logic signed [8:0]      characteristic_or_exponent;
    logic [N-6:0]           mantissa_bits;
    logic [$clog2(N-4)-1:0] precision;
    logic                   is_zero;
    logic                   is_nar;

    predecoder #(
        .N(N),
        .OUTPUT_EXPONENT(1'b0)
    ) dut (
        .takum                      (takum),
        .sign_bit                   (sign_bit),
        .characteristic_or_exponent (characteristic_or_exponent),
        .mantissa_bits              (mantissa_bits),
        .precision                  (precision),
        .is_zero                    (is_zero),
        .is_nar                     (is_nar)
    );

    integer fd, code, errors, count;
    string  vecfile;

    // Reference fields read from the vector file
    logic [N-1:0] takum_v;
    integer       s_ref, coe_ref, prec_ref, iz_ref, inar_ref;
    logic [N-6:0] mant_ref;

    initial begin
        errors = 0;
        count  = 0;
        if (!$value$plusargs("VEC=%s", vecfile)) begin
            $display("FATAL: no +VEC=<file> given");
            $fatal;
        end
        fd = $fopen(vecfile, "r");
        if (fd == 0) begin
            $display("FATAL: cannot open %s", vecfile);
            $fatal;
        end

        while (!$feof(fd)) begin
            code = $fscanf(fd, "%b %d %d %b %d %d %d\n",
                           takum_v, s_ref, coe_ref, mant_ref,
                           prec_ref, iz_ref, inar_ref);
            if (code != 7) continue;

            takum = takum_v;
            #1;
            count = count + 1;

            if (sign_bit !== s_ref[0]) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("MISMATCH takum=%b sign rtl=%b ref=%0d", takum, sign_bit, s_ref);
            end
            if ($signed(characteristic_or_exponent) !== coe_ref) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("MISMATCH takum=%b char rtl=%0d ref=%0d",
                             takum, $signed(characteristic_or_exponent), coe_ref);
            end
            if (mantissa_bits !== mant_ref) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("MISMATCH takum=%b mant rtl=%b ref=%b", takum, mantissa_bits, mant_ref);
            end
            if (precision !== prec_ref[$clog2(N-4)-1:0]) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("MISMATCH takum=%b prec rtl=%0d ref=%0d", takum, precision, prec_ref);
            end
            if (is_zero !== iz_ref[0]) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("MISMATCH takum=%b is_zero rtl=%b ref=%0d", takum, is_zero, iz_ref);
            end
            if (is_nar !== inar_ref[0]) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("MISMATCH takum=%b is_nar rtl=%b ref=%0d", takum, is_nar, inar_ref);
            end
        end
        $fclose(fd);

        if (errors == 0)
            $display("PASS: predecoder N=%0d, %0d vectors, 0 mismatches.", N, count);
        else
            $display("FAIL: predecoder N=%0d, %0d vectors, %0d mismatches.", N, count, errors);
    end

endmodule
